### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by jkl469** [ltkong218/FastFlowNet#20]
run on colab.research.google.com;
and output:
sh: 1: ping: not found
sh: 1: ping: not found
sh: 1: ping: not found
sh: 1: ping: not found
Traceback (most recent call last):
  File "/content/drive/MyDrive/FastFlowNet-main/demo.py", line 45, in <module>
    output = model(input_t).data
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/FastFlowNet-main/models/FastFlowNet.py", line 134, in forward
    cv6 = torch.index_select(self.corr(f16, f26), dim=1, index=self.index.to(f16).long())
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/FastFlowNet-main/models/correlation_package/correlation.py", line 59, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/function.py", line 262, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

**Comment by ltkong218** [comment]
Which version of PyTorch do you use? Have you successfully installed the [<code>Pytorch-Correlation-extension</code>](https://github.com/ClementPinard/Pytorch-Correlation-extension) module?
