### ISSUE TITLE
I meet some questions No module named 'correlation_cuda'

### ISSUE THREAD

**Issue by huangjiangui** [ltkong218/FastFlowNet#26]
(base) root@autodl-container-c6d211963c-81d44250:~/autodl-fs/FastFlowNet-main# python benchmark.py
Traceback (most recent call last):
  File "benchmark.py", line 5, in <module>
    from models.FastFlowNet import FastFlowNet
  File "/root/autodl-fs/FastFlowNet-main/models/FastFlowNet.py", line 5, in <module>
    from .correlation_package.correlation import Correlation
  File "/root/autodl-fs/FastFlowNet-main/models/correlation_package/correlation.py", line 4, in <module>
    import correlation_cuda
ModuleNotFoundError: No module named 'correlation_cuda'
(base) root@autodl-container-c6d211963c-81d44250:~/autodl-fs/FastFlowNet-main#

**Comment by ltkong218** [comment]
May be you should replace <code>from models.FastFlowNet import FastFlowNet</code> with <code>from models.FastFlowNet_v2 import FastFlowNet</code> in <code>benchmark.py</code>. Also, please refer to the [README.md](https://github.com/ltkong218/FastFlowNet/blob/main/README.md) file to configure the correct environment.
